### ISSUE TITLE
emit a single line on errors when `--filebeat` is used

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#324] opened 2023-01-16 15:37 UTC
### Problem Description

When `--filebeat` is used and an error is raised, we should emit a single line 

https://github.com/elastic/enterprise-search-team/issues/3706

**Comment by DianaJourdan** [comment] 2023-04-18 14:19
Is it a duplicate of https://github.com/elastic/enterprise-search-team/issues/3706?

**Comment by seanstory** [comment] 2023-09-18 20:23
Yes, this is a duplicate. Closing

**Closed by seanstory** 2023-09-18 20:23 UTC
Labels: tech-improvement
