### ISSUE TITLE
Unexpected text extraction failures report non-actionable errors

### ISSUE THREAD

**Issue by artem-shelkovnikov** [elastic/connectors-python#1155] opened 2023-06-30 11:00 UTC
## Bug Description
When unexpected text extraction error happens, sometimes no error is reported and it's not possible to act on it

### To Reproduce
1. Create a Sharepoint Online connector that will sync all site collections (*)
2. Start a sync and observe logs
3. See error:
```
[FMWK][12:58:32][ERROR] Text extraction unexpectedly failed. Error:
[FMWK][12:58:44][ERROR] Text extraction unexpectedly failed. Error:
```

## Expected behavior
Error is communicated clearly.

**Comment by seanstory** [comment] 2023-07-06 15:21
@navarone-feekery to confirm if this is still an issue

**Comment by navarone-feekery** [comment] 2023-07-10 10:09
I confirmed that this is still occurring, I'll investigate.

**Comment by navarone-feekery** [comment] 2023-07-11 14:10
Actually, I was mistaken -- this doesn't happen anymore.
A similar error was happening, and it also happens when not using local text extraction. When I run a full sync on the enterprise search sites, I occasionally get `Exception found for task Task-5802:` with no actionable information.

**Comment by artem-shelkovnikov** [comment] 2023-07-12 09:05
@navarone-feekery it can probably be closed now then - there's another issue for the empty "Exception found for task" exception: https://github.com/elastic/connectors-python/issues/789

**Comment by navarone-feekery** [comment] 2023-07-12 10:51
I did one more sync on the full enterprise search collection and couldn't reproduce (just to quadruple check) and it isn't occurring anymore, so I'll close this.

**Closed by navarone-feekery** 2023-07-12 10:51 UTC
Labels: bug, team:ingestion, v8.9.0, effort:low, priority:low
