### ISSUE TITLE
Execution of native connectors seem to be overlapping during sync while paralelly executing other connectors

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#1043] opened 2023-06-09 07:09 UTC
## Bug Description
Execution of native connectors seem to be overlapping during sync while paralelly executing other connectors
While running Connectors in native mode, the sync overlaps with already running sync of other connector i.e sync running for non-native connectors

### To Reproduce

1. Non-native connector already running in elastic cloud deployment
2. Paralelly run the ABS connector in native mode by configuring the same elastic cloud deployment credentials
3. Observe the logs displayed on console and kibana

## Expected behavior
No Error should be displayed and Azure Blob Storage Connector should run successfully

## Actual behavior
The connector execution of Azure Blob Storage is overlapping with the non-native connector execution and logs with error is displayed in the execution where non-native connector is executed

Note - Attached error logs for reference

## Environment
Elastic Cloud v8.8.0
CentOS v7
[error.log](https://github.com/elastic/connectors-python/files/11703285/error.log)

**Comment by prashant-elastic** [comment] 2023-06-09 08:28
This issue is not specific to any connector. It could appear while executing any non-native and native connector parallelly . Therefore, Assuming to be a framework related issue.

**Comment by khushbu-elastic** [comment] 2023-06-12 05:27
Azure Blog Storage was connected to Elastic Cloud in native mode and Servicenow/GitHub was running as self managed connector client . And the native connector i.e ABS was overlapping on its the execution

**Comment by sphilipse** [comment] 2023-06-12 12:27
It's unclear to me what 'overlapping' means, or what the problem is, exactly. Are multiple connectors picking up the same sync jobs?

**Comment by khushbu-elastic** [comment] 2023-06-12 13:01
@sphilipse The sync jobs are different (executing on different VMs) but the logs for both the jobs are shown only on one VM. 
This was reproducible randomly.

**Comment by sphilipse** [comment] 2023-06-12 13:13
If the logs are showing up on a specific VM (connector instance), then that means that connector instance is executing that sync. It's more likely that the native connector in cloud is picking up this connector and syncing it, and your on-premises native connector client is never getting to it.

**Comment by khushbu-elastic** [comment] 2023-06-12 13:35
At both the connector instances (on 2 different VMs), parallelly execution is on-going for both the connectors - Native ABS Connector & Github Connector Client (non-native connector).
The logs for both the executions are getting displayed only on one VM, which is a bug.

**Comment by khushbu-elastic** [comment] 2023-06-14 09:07
@sphilipse We tried removing the list of the native_service_types other than the one connector which we are checking and it worked fine. The logs are displayed correctly. So closing this issue for now.

**Closed by khushbu-elastic** 2023-06-14 09:07 UTC
Labels: bug
