### ISSUE TITLE
Facing issues in sharepoint indexing while testing with large dataset

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#615] opened 2023-03-23 10:12 UTC
## Bug Description
Facing issues in indexing while testing with large dataset while testing the performance

### To Reproduce
1. Add host, api_key, connector ID and service type in config.yml file
2. Execute command make run
3. Update sharepoint configurations on the Kibana UI
4. Click Sync button to index data from source to kibana

## Expected behavior
All the data should be successfully indexed in Elasticsearch

## Actual behavior
Getting error 429: Too many requests and data does not get indexed successfully

## Additional context
The API request limit for sharepoint requests is 1200/min, so server is not able to handle API requests exceeding this limit

**Comment by serenachou** [comment] 2023-04-12 19:55
cc @DianaJourdan @danajuratoni  @tarekziade

**Comment by artem-shelkovnikov** [comment] 2023-05-04 15:37
Duplicate of: https://github.com/elastic/connectors-python/issues/615

**Closed as completed by artem-shelkovnikov** 2023-05-04 15:37 UTC
Labels: bug, sharepoint
