### ISSUE TITLE
[Sharepoint Server] : Connector not getting executed when Enable SSL parameter is set as False

### ISSUE THREAD

**Issue by prashant-elastic** [elastic/connectors-python#1150] opened 2023-06-30 07:50 UTC
## Bug Description
Sharepoint Server Connector not getting executed when Enable SSL parameter is set as False

### To Reproduce
1. Take the latest code from connectors-python repo
2. On Elasticsearch instance v8.9.0-SNAPSHOT , create an index
3. Do all the necessary configurations in connector config file i.e API key and connector_id
4. Execute make run command
5. Go to Elasticsearch index and do all the necessary configurations related to sharepoint server
6. Click on Sync > Full content
7. Observe the error displayed on the console

## Expected behavior
Connector execution should be successful and documents should be ingested successfully

## Actual behavior
Error is thrown as "Field validation errors: 'SSL certificate' cannot be empty" and connector execution is interuptted.

## Screenshots

<img width="1440" alt="Screen Shot 2023-06-30 at 12 41 37 PM" src="https://github.com/elastic/connectors-python/assets/103035276/7721ffda-89a3-4783-aa08-85f19c4abab1">

## Environment
CentOS 7
Elastic Cloud v8.9.0-SNAPSHOT

**Comment by khushbu-elastic** [comment] 2023-06-30 13:24
@DianaJourdan  @danajuratoni  I have also checked for Confluence connector with SSL enabled as False and showing the same error as attached and mentioned by @prashant-elastic. PFA
![image (4)](https://github.com/elastic/connectors-python/assets/133654004/d930d09c-1d35-4f23-badd-7d95a2b3dd2f)

This seems an issue with all the connectors where SSL is involved and because of it we won't be able to verify the QA checklist for 8.9.

Please check this and let us know.

**Comment by artem-shelkovnikov** [comment] 2023-06-30 13:56
Should be fixed by https://github.com/elastic/kibana/pull/160923 when next BC is available

**Comment by artem-shelkovnikov** [comment] 2023-06-30 13:57
Closing as duplicate of https://github.com/elastic/enterprise-search-team/issues/4985 (internal issue)

**Closed by artem-shelkovnikov** 2023-06-30 13:57 UTC
Labels: bug
