### ISSUE TITLE
[proposal] disk-based id lookups

### ISSUE THREAD

**Issue by tarekziade** [elastic/connectors-python#748] opened 2023-04-06 15:41 UTC
### Problem Description

We currently scroll all ids into memory to do a sync

https://github.com/elastic/connectors-python/blob/main/connectors/byoei.py#L476

and they are kept in memory here:

https://github.com/elastic/connectors-python/blob/main/connectors/byoei.py#L589

That's our main RAM bottleneck for warm syncs on large collections

### Proposed solution

Let's create a `ElasticIndexIds` class that wraps this work and use a disk-based storage for ids with fast lookups.

I benched `dbm` and `sqlite3` for 1 Million docs -- dbm wins see https://github.com/tarekziade/bench-db

**Comment by artem-shelkovnikov** [comment] 2023-08-11 13:20
Duplicate of https://github.com/elastic/enterprise-search-team/issues/3242

**Closed by artem-shelkovnikov** 2023-08-11 13:20 UTC
Labels: tech-debt

**Comment by jedrazb** [comment] 2024-06-14 11:11
That looks very promising! Great that we have some handy benchmarks ready https://github.com/tarekziade/bench-db! I'm checking how would rocksDB perform against them, [Flink uses rocksDB to store internal state](https://flink.apache.org/2021/01/18/using-rocksdb-state-backend-in-apache-flink-when-and-how/)
